export const exclude = [
  '/user/login',
  '/user/signup',
  '/user/auth/login',
  '/user/forgot-password',
  'user/reset-password/:u_id',
  '/host/signup',
  '/host/login',
  '/host/forgot-password',
  'host/reset-password/:h_id',
  '/host/auth/login',
  '/host/verify-otp',
  '/admin/login',
  '/admin/getFile/:filename',
];
